export const FOGGIA_CITIES = [
  'Foggia',
  'Manfredonia',
  'Vieste',
  'Monte Sant\'Angelo',
  'San Giovanni Rotondo',
  'Lucera',
  'Cerignola',
  'San Severo',
  'Peschici',
  'Rodi Garganico',
  'Ischitella',
  'Vico del Gargano',
  'Mattinata',
  'Zapponeta',
  'Margherita di Savoia',
  'Trinitapoli',
  'San Marco in Lamis',
  'Apricena',
  'Torremaggiore',
  'Accadia',
  'Bovino',
  'Deliceto',
  'Orta Nova',
  'Stornara',
  'Stornarella',
  'Carapelle',
  'Ordona',
  'Lesina',
  'Serracapriola',
  'Chieuti',
  'Poggio Imperiale',
  'Cagnano Varano',
  'Carpino',
  'Ischitella',
]

export const CATEGORIES = {
  horeca: {
    label: 'HoReCa / Take Away',
    icon: '🍕',
    color: 'orange',
    subcategories: [
      { value: 'pizzeria', label: 'Pizzeria' },
      { value: 'bar', label: 'Bar / Caffetteria' },
      { value: 'ristorante', label: 'Ristorante' },
      { value: 'panificio', label: 'Panificio' },
      { value: 'pasticceria', label: 'Pasticceria' },
      { value: 'street_food', label: 'Street Food' },
      { value: 'sushi_takeaway', label: 'Sushi / Take Away' },
      { value: 'rosticceria', label: 'Rosticceria' },
      { value: 'pub', label: 'Pub / Birreria' },
      { value: 'gelateria', label: 'Gelateria' },
    ],
  },
  alimentari_retail: {
    label: 'Alimentari / Retail',
    icon: '🛒',
    color: 'green',
    subcategories: [
      { value: 'alimentari', label: 'Alimentari Indipendenti' },
      { value: 'minimarket', label: 'Market / Minimarket' },
      { value: 'supermercato', label: 'Supermercato Locale' },
      { value: 'macelleria', label: 'Macelleria' },
      { value: 'pescheria', label: 'Pescheria' },
      { value: 'fruttivendolo', label: 'Fruttivendolo / Ortofrutta' },
      { value: 'detersivista', label: 'Detersivista (no catene)' },
      { value: 'caseificio', label: 'Piccolo Caseificio' },
      { value: 'enoteca', label: 'Enoteca / Vinoteca' },
    ],
  },
  medical_estetico: {
    label: 'Medical / Estetico',
    icon: '💊',
    color: 'blue',
    subcategories: [
      { value: 'studio_dentistico', label: 'Studio Dentistico' },
      { value: 'ambulatorio', label: 'Ambulatorio Medico' },
      { value: 'rsa', label: 'RSA / Casa di Riposo' },
      { value: 'clinica_privata', label: 'Clinica Privata' },
      { value: 'centro_estetico', label: 'Centro Estetico' },
      { value: 'laboratorio_medico', label: 'Laboratorio Medico' },
      { value: 'fisioterapia', label: 'Studio Fisioterapia' },
      { value: 'veterinario', label: 'Clinica Veterinaria' },
    ],
  },
  altre_attivita: {
    label: 'Altre Attività',
    icon: '🎨',
    color: 'purple',
    subcategories: [
      { value: 'centro_tattoo', label: 'Centro Tattoo / Piercing' },
      { value: 'parrucchiere', label: 'Parrucchiere' },
      { value: 'barbiere', label: 'Barbiere' },
      { value: 'lavanderia', label: 'Lavanderia' },
      { value: 'palestra', label: 'Palestra / Centro Fitness' },
    ],
  },
}

export const STATUS_CONFIG = {
  da_contattare:    { label: 'Da Contattare', color: 'slate' },
  contattato:       { label: 'Contattato',    color: 'blue' },
  richiamare:       { label: 'Da Richiamare', color: 'yellow' },
  cliente_acquisito:{ label: 'Acquisito ✓',   color: 'green' },
  non_interessato:  { label: 'Non Interessato', color: 'red' },
}

export const VISIT_TYPES = [
  { value: 'chiamata', label: '📞 Chiamata' },
  { value: 'visita', label: '🚗 Visita in loco' },
  { value: 'email', label: '✉️ Email' },
  { value: 'whatsapp', label: '💬 WhatsApp' },
]
